occupations:
  'エンジニア・技術職（システム/ネットワーク）':
    - システム開発（Web/オープン系）
    - システム開発（モバイル系）
    - システム開発（制御・組み込み）
    - システム開発（汎用系）
    - ネットワーク/サーバ監視・運用・保守・技術サポート
    - ネットワーク/サーバ設計・構築
    - パッケージソフト・ミドルウェア開発
    - プロジェクトマネージャー（PM）・リーダー
    - プロダクトマネージャー
    - 社内情報システムエンジニア（社内SE）
    - ITコンサルタント・プリセールス
    - データサイエンティスト
    - その他システム関連
  'エンジニア・技術職（電気/電子/機械/半導体）':
    - 生産技術（設備）・生産管理・プロセス開発
    - 自動車・建機・輸送機器
    - アナログ/デジタル半導体・システム・回路設計
    - 精密機器・電子機器・計測機器
    - その他技術関連
  'クリエイティブ職（Web）':
    - Webコーダー・HTMLコーダー
    - Webサービス・コンテンツ企画
    - Webデザイナー・UI/UXデザイナー
    - Webプロデューサー・Webディレクター
    - Webライター・Web編集
  '企画・マーケティング職':
    - マーケ・広告宣伝・販促・PR
    - 事業企画・事業統括
    - カスタマーサービス（CS）・ユーザーサポート
    - Webコンサルタント・SEO・SEM
    - 商品企画・サービス企画
  '経営・CxO職':
    - CEO・経営企画・経営管理
    - CFO
    - CMO
    - COO
    - CTO・CIO
  '経理・管理・バックオフィス職':
    - 人事・総務
    - 広報・IR
    - 法務（コンプライアンス）・知的財産・特許
    - 財務・会計・経理
    - 物流管理・貿易事務
  'サービス職（人材/店舗/医療）':
    - 店長・販売・店舗管理・接客
    - スーパーバイザー（SV）・エリアマネージャー
    - 医療・福祉・介護サービス
    - キャリアコンサルタント/コーディネーター・カウンセラー
    - 購買・調達・MD・バイヤー・店舗開発
    - その他サービス関連
  '専門職（金融/不動産/コンサルタント/士業）':
    - 金融・保険・ファイナンシャルプランナー（FP）
    - 不動産・住宅コンサルタント
    - 組織・人事コンサルタント
    - 経営・戦略コンサルタント
    - 財務・会計コンサルタント
    - その他コンサル・専門職関連
  '建築設計・土木・プラント職':
    - 施工管理・環境調査・分析
    - 測量・設計・積算・計装
    - その他建築・土木・プラント関連
  '営業職':
    - 代理店営業・パートナーセールス
    - 企画営業・アカウントプランナー
    - 個人営業
    - 内勤営業・カウンターセールス
    - 医療営業（MR/MS）
    - 営業マネージャー・営業管理職
    - 営業企画
    - 新規開拓営業
    - 海外営業
    - コールセンター運営・オペレーター
    - セールスエンジニア・技術営業（FAE）
    - ルートセールス
    - その他営業関連
  'アシスタント・事務職・オフィスワーク':
    - 一般事務・営業事務・庶務・秘書
    - 通訳・翻訳
    - その他受付・企画・事務関連

technics:
  - ASP
  - ASP.NET
  - AWS
  - Alexa
  - Android
  - Angular2
  - AngularJS
  - Apache
  - Arduino
  - Azure
  - Backborn.js
  - Blockchain
  - C
  - C#
  - C++
  - COBOL
  - CSS3
  - CakePHP
  - Catalyst
  - Chainer
  - Clojure
  - CodeIgniter
  - CoffeeScript
  - Coldfusion
  - Cordova
  - Couchbase
  - DDD
  - Dart
  - DeepLearning
  - Delphi
  - Django
  - Elasticsearch
  - Electron
  - Elixir
  - Erlang
  - Ethereum
  - Express
  - FPGA
  - Fargate
  - Firebase
  - Flash
  - Flask
  - Fuel
  - PHP
  - Go
  - GoogleCloudPlatform
  - GoogleHome
  - Groovy
  - HBase
  - HTML5
  - Hadoop
  - Haskell
  - Heroku
  - IoT
  - JSP
  - Java
  - JavaScript
  - Jenkins
  - Jupyter
  - Keras
  - Kotlin
  - Lua
  - MachineLearning
  - Mojolicious
  - MongoDB
  - MySQL
  - Nagios
  - Node.js
  - Objective-C
  - OpenCV
  - PHP
  - PL/1
  - Pepper
  - Perl
  - Phoenix
  - PhoneGap
  - Photon
  - PlayFramework
  - PostgreSQL
  - PowerShell
  - Python
  - R
  - RHEL7
  - ROS
  - RPG
  - RaspberryPi
  - React
  - ReactJS
  - Redis
  - Ruby
  - RubyonRails
  - RubyOnRails
  - SAP
  - SQL
  - SQLServer
  - SRE
  - Salesforce
  - Scala
  - Seasar
  - Sinatra
  - Spark
  - Splunk
  - Struts
  - Struts2
  - Swift
  - Symfony
  - TensorFlow
  - TypeScript
  - UE4
  - Unity
  - Unity3D
  - VBA
  - VR
  - VisualBasic.NET
  - VisualC#.NET
  - VisualBasic
  - WPF
  - Watson
  - WebVR
  - WordPress
  - XML
  - Xamarin
  - ZendFramework
  - angular
  - cakephp3
  - cocos2d
  - cocos2d-x
  - docker
  - es6
  - fluentd
  - gcp
  - golang
  - iOS
  - ibmcloud
  - jQuery
  - jQueryMobile
  - java8
  - juniper
  - kubernetes
  - lambda
  - laravel
  - mariadb
  - matplotlib
  - nginx
  - nodejs
  - nuxt.js
  - oracle
  - pandas
  - processing
  - python3
  - reactnative
  - redux
  - rust
  - scikit-learn
  - spring
  - vue.js
  - zabbix
  - アセンブラ

industries:
  'IT/Web・通信・インターネット系':
    - システムインテグレータ・ソフトハウス
    - 通信キャリア・データセンター・ISP
    - インターネット/Webサービス・ASP
    - Webマーケティング・ネット広告
    - モバイル/アプリサービス
    - ITコンサルティング
    - ソフトウェア/パッケージベンダ
    - その他IT/Web・通信・インターネット系
    - IoT・M2M・ロボット
    - AR/VR/MR
  'マスコミ・エンターテイメント・メディア系':
    - 放送（テレビ/ラジオ）・音楽・芸能
    - 出版・新聞・雑誌
    - ゲーム・エンタメ
    - 広告・デザイン・イベント
    - その他マスコミ・エンターテイメント・メディア系
  'サービス系':
    - 人材サービス（紹介/派遣/教育/研修）
    - 飲食・旅行・レジャー・アミューズメント
    - 医療・福祉・介護サービス
    - その他サービス系
  '製造・メーカー系':
    - 電気・電子・機械・半導体
    - 医薬品・医療機器
    - 化粧品・アパレル
    - 食料品・日用品・雑貨・文具
    - その他メーカー系
  'コンサルティング・リサーチ':
    - 経営/ビジネスコンサルティング・シンクタンク
    - その他コンサルティング系
  '商社（卸売）・流通・小売り系':
    - 総合商社・専門商社
    - 物流・運送・倉庫・梱包
    - その他商社・流通・小売系
  '金融・保険系':
    - 銀行・信用金庫・組合
    - プライベートエクイティ・ベンチャーキャピタル（VC）
    - 証券・投資銀行
    - 生命保険・損害保険
    - その他金融・保険系
  '不動産・建設系':
    - 建築・土木・設計
    - 不動産賃貸・仲介・管理
    - プラント・設備管理・建材
    - その他不動産・建設系
  'その他':
    - その他業界